<?php

namespace Aurimas\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function findByUsername($username)
    {
        $qb = $this->createQueryBuilder('u')
            ->where('u.username = :username')
            ->setParameter('username', $username);

        $query = $qb->getQuery();
        $query->useResultCache(true, 3600, 'user_' . $username);
        return $query->getResult();
    }
}
